'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import type { EventView } from '@kurasikapa/web-kit/bff/events'
import type { MediaAssetView } from '@kurasikapa/web-kit/bff/media-library'
import { createEventAction } from '@/actions/events'

type Kind = EventView['type']; type Mode = EventView['mode']

export function EventManager({ locale, events, assets }: { locale: string; events: readonly EventView[]; assets: readonly MediaAssetView[] }): React.ReactElement {
  const router = useRouter(); const [kind, setKind] = useState<Kind>('conference'); const [mode, setMode] = useState<Mode>('hybrid'); const [imageID, setImageID] = useState(''); const [featured, setFeatured] = useState(false); const [message, setMessage] = useState<string | null>(null); const [pending, start] = useTransition()
  const images = assets.filter((asset) => asset.kind === 'image' && asset.status === 'ready')
  const submit = (data: FormData): void => { start(async () => {
    const title = value(data, 'title'); const startsAt = accraISO(value(data, 'startsAt')); const endsAt = accraISO(value(data, 'endsAt'))
    const result = await createEventAction({ type: kind, mode, title, slug: slug(title), locale, summary: value(data, 'summary'), timezone: 'Africa/Accra', venue: value(data, 'venue'), city: value(data, 'city'), registrationURL: value(data, 'registrationURL'), startsAt, endsAt, ...(imageID === '' ? {} : { imageAssetID: imageID }), speakers: value(data, 'speakers').split(',').map((speaker) => speaker.trim()).filter(Boolean), featured })
    if (!result.ok) { setMessage(result.error.message); return }
    setMessage('Event published to the public calendar.'); router.refresh()
  }) }
  return <div className="grid gap-7 xl:grid-cols-[minmax(0,1.2fr)_minmax(22rem,.8fr)]"><section className="border border-outline-variant bg-surface-container-lowest p-6 shadow-[8px_9px_0_rgba(16,75,42,.12)]"><p className="broadcast-kicker text-primary">Events desk</p><h2 className="mt-2 font-display text-3xl font-bold">Publish an event</h2><form action={submit} className="mt-6 space-y-5"><Choice label="Format" items={[['webinar','Webinar'],['conference','Conference'],['summit','Summit']]} selected={kind} onSelect={(id) => { setKind(id as Kind) }}/><Choice label="Attendance" items={[['online','Online'],['in_person','In person'],['hybrid','Hybrid']]} selected={mode} onSelect={(id) => { setMode(id as Mode) }}/><Field name="title" label="Event title" placeholder="Kurasikapa Media Futures Summit"/><TextArea name="summary" label="Public summary" placeholder="Explain who should attend, what they will learn and why this gathering matters."/><div className="grid gap-4 md:grid-cols-2"><Field name="startsAt" label="Starts in Accra" type="datetime-local"/><Field name="endsAt" label="Ends in Accra" type="datetime-local"/></div>{mode !== 'online' && <div className="grid gap-4 md:grid-cols-2"><Field name="venue" label="Venue" placeholder="National Theatre"/><Field name="city" label="City" placeholder="Accra"/></div>}<Field name="registrationURL" label="Registration link" type="url" placeholder="https://events.example.org/register" optional/><Field name="speakers" label="Speakers" placeholder="Ama Mensah, Kwesi Boateng" optional/><ImageChoice images={images} selected={imageID} onSelect={setImageID}/><label className="flex items-start gap-3 border border-outline-variant bg-surface-container-low p-4"><input type="checkbox" checked={featured} onChange={(event) => { setFeatured(event.target.checked) }} className="mt-1 size-4 accent-primary"/><span><strong className="block text-sm">Feature this event</strong><small className="text-on-surface-variant">Use it as the lead event while it remains upcoming.</small></span></label><button disabled={pending} className="bg-primary px-5 py-3 text-sm font-bold text-on-primary disabled:cursor-wait disabled:opacity-45">{pending ? <span className="inline-flex items-center gap-2">Publishing <Dots/></span> : 'Publish event'}</button>{message !== null && <p role="status" className="border-l-4 border-secondary bg-secondary-container/30 p-3 text-sm">{message}</p>}</form></section><EventList events={events}/></div>
}

function EventList({ events }: { events: readonly EventView[] }): React.ReactElement { return <section className="border border-outline-variant bg-surface-container-lowest p-6 shadow-[8px_9px_0_rgba(16,75,42,.12)]"><p className="broadcast-kicker text-primary">Public calendar</p><h2 className="mt-2 font-display text-3xl font-bold">Upcoming</h2>{events.length === 0 ? <Empty/> : <div className="mt-6 space-y-4">{events.map((event) => <article key={event.id} className="border border-outline-variant bg-surface-container-low p-5"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-primary-ink">{event.type.replace('_',' ')} · {formatDate(event.startsAt)}</span><h3 className="mt-2 font-display text-2xl font-bold">{event.title}</h3><p className="mt-2 text-sm text-on-surface-variant">{event.summary}</p></article>)}</div>}</section> }
function ImageChoice({ images, selected, onSelect }: { images: readonly MediaAssetView[]; selected: string; onSelect: (id: string) => void }): React.ReactElement { return <fieldset><legend className="mb-3 text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">Feature image (optional)</legend>{images.length === 0 ? <p className="border-l-4 border-secondary bg-secondary-container/30 p-4 text-sm">Upload an accessible image in Media Library to add event photography.</p> : <div className="grid gap-3 sm:grid-cols-2">{images.map((image) => <button key={image.id} type="button" aria-pressed={selected === image.id} onClick={() => { onSelect(selected === image.id ? '' : image.id) }} className={`border p-3 text-left ${selected === image.id ? 'border-primary bg-primary/10 shadow-[4px_5px_0_rgba(16,75,42,.15)]' : 'border-outline-variant'}`}><strong className="block truncate text-sm">{image.filename}</strong><span className="mt-1 block line-clamp-2 text-xs text-on-surface-variant">{image.altText}</span></button>)}</div>}</fieldset> }
function Choice({ label, items, selected, onSelect }: { label: string; items: readonly (readonly [string,string])[]; selected: string; onSelect: (id: string) => void }): React.ReactElement { return <fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">{label}</legend><div className="flex flex-wrap gap-2">{items.map(([id,itemLabel]) => <button key={id} type="button" aria-pressed={selected === id} onClick={() => { onSelect(id) }} className={`border px-3 py-2 text-xs font-bold ${selected === id ? 'border-primary bg-primary text-on-primary' : 'border-outline-variant hover:border-primary'}`}>{itemLabel}</button>)}</div></fieldset> }
function Field({ name, label, placeholder = '', type = 'text', optional = false }: { name: string; label: string; placeholder?: string; type?: string; optional?: boolean }): React.ReactElement { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">{label}</span><input name={name} type={type} required={!optional} placeholder={placeholder} className="h-12 w-full border border-outline-variant bg-surface px-4 focus:border-primary focus:outline-none"/></label> }
function TextArea({ name, label, placeholder }: { name: string; label: string; placeholder: string }): React.ReactElement { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">{label}</span><textarea name={name} required rows={4} placeholder={placeholder} className="w-full border border-outline-variant bg-surface p-4 focus:border-primary focus:outline-none"/></label> }
function Empty(): React.ReactElement { return <div className="signal-grid mt-6 border border-outline-variant p-8 text-center"><span aria-hidden className="mx-auto grid size-12 animate-pulse place-items-center bg-primary text-xl text-on-primary">◇</span><h3 className="mt-4 font-display text-xl font-bold">The events desk is ready.</h3><p className="mt-2 text-sm text-on-surface-variant">Publish the first approved webinar, conference or summit to fill this calendar.</p></div> }
function Dots(): React.ReactElement { return <span aria-hidden className="inline-flex gap-1"><i className="size-1 animate-bounce rounded-full bg-current"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:120ms]"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:240ms]"/></span> }
function value(data: FormData, name: string): string { const item = data.get(name); return typeof item === 'string' ? item : '' }
function slug(input: string): string { return input.toLowerCase().normalize('NFKD').replace(/\p{M}/gu, '').trim().replace(/[^a-z0-9]+/gu, '-').replace(/^-|-$/gu, '') }
function accraISO(input: string): string { return input === '' ? '' : `${input}:00.000Z` }
function formatDate(input: string): string { return new Intl.DateTimeFormat('en-GH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Africa/Accra' }).format(new Date(input)) }
