'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import type { GalleryView } from '@kurasikapa/web-kit/bff/galleries'
import type { MediaAssetView } from '@kurasikapa/web-kit/bff/media-library'
import { createGalleryAction } from '@/actions/galleries'

type Kind = 'photo' | 'video'
interface ItemDraft { caption: string; credit: string; captionAssetID: string }

export function GalleryManager({ locale, galleries, assets }: { locale: string; galleries: readonly GalleryView[]; assets: readonly MediaAssetView[] }): React.ReactElement {
  const router = useRouter(); const [kind, setKind] = useState<Kind>('photo'); const [selected, setSelected] = useState<string[]>([]); const [drafts, setDrafts] = useState<Record<string, ItemDraft>>({}); const [message, setMessage] = useState<string | null>(null); const [pending, start] = useTransition()
  const usable = assets.filter((asset) => asset.status === 'ready' && asset.kind === (kind === 'photo' ? 'image' : 'video'))
  const captions = assets.filter((asset) => asset.status === 'ready' && asset.kind === 'caption')
  const chooseKind = (next: Kind): void => { setKind(next); setSelected([]); setDrafts({}); setMessage(null) }
  const toggle = (id: string): void => { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); setDrafts((current) => ({ ...current, [id]: current[id] ?? { caption: '', credit: '', captionAssetID: '' } })) }
  const update = (id: string, field: keyof ItemDraft, value: string): void => { setDrafts((current) => ({ ...current, [id]: { ...(current[id] ?? { caption: '', credit: '', captionAssetID: '' }), [field]: value } })) }
  const submit = (data: FormData): void => { start(async () => {
    const title = value(data, 'title'); const items = selected.map((assetID) => ({ assetID, caption: drafts[assetID]?.caption ?? '', credit: drafts[assetID]?.credit ?? '', ...(kind === 'video' ? { captionAssetID: drafts[assetID]?.captionAssetID ?? '' } : {}) }))
    const result = await createGalleryAction({ kind, title, slug: slug(title), locale, summary: value(data, 'summary'), items })
    if (!result.ok) { setMessage(result.error.message); return }
    setMessage('Gallery published to the visual newsroom.'); setSelected([]); setDrafts({}); router.refresh()
  }) }
  return <div className="grid gap-7 xl:grid-cols-[minmax(0,1.2fr)_minmax(22rem,.8fr)]"><section className="border border-outline-variant bg-surface-container-lowest p-6 shadow-[8px_9px_0_rgba(16,75,42,.12)]"><p className="broadcast-kicker text-primary">Visual desk</p><h2 className="mt-2 font-display text-3xl font-bold">Build a gallery</h2><form action={submit} className="mt-6 space-y-5"><Choice label="Gallery format" items={[{ id: 'photo', label: 'Photo story' }, { id: 'video', label: 'Video reports' }]} selected={kind} onSelect={(id) => { chooseKind(id as Kind) }}/><Field name="title" label="Gallery title" placeholder="Inside Accra's changing markets"/><TextArea name="summary" label="Editorial summary" placeholder="Explain what the audience will see, why it matters and where the reporting took place."/><fieldset><legend className="mb-3 text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">Select verified {kind === 'photo' ? 'images' : 'videos'}</legend>{usable.length === 0 ? <Empty text={`Upload ready ${kind === 'photo' ? 'images with alt text' : 'videos and captions'} in the Media Library first.`}/> : <div className="grid gap-3 sm:grid-cols-2">{usable.map((asset) => <button key={asset.id} type="button" aria-pressed={selected.includes(asset.id)} onClick={() => { toggle(asset.id) }} className={`min-h-24 border p-4 text-left ${selected.includes(asset.id) ? 'border-primary bg-primary/10 shadow-[4px_5px_0_rgba(16,75,42,.16)]' : 'border-outline-variant hover:border-primary'}`}><strong className="block truncate">{asset.filename}</strong><span className="mt-2 block text-xs text-on-surface-variant">{asset.mimeType} · {formatBytes(asset.bytes)}</span></button>)}</div>}</fieldset>{selected.map((id) => <ItemFields key={id} id={id} name={usable.find((asset) => asset.id === id)?.filename ?? id} kind={kind} draft={drafts[id]} captions={captions} onUpdate={update}/>)}<button disabled={pending || selected.length === 0} className="bg-primary px-5 py-3 text-sm font-bold text-on-primary disabled:cursor-wait disabled:opacity-45">{pending ? <span className="inline-flex items-center gap-2">Publishing <Dots/></span> : `Publish ${kind} gallery`}</button>{message !== null && <p role="status" className="border-l-4 border-secondary bg-secondary-container/30 p-3 text-sm">{message}</p>}</form></section><GalleryList galleries={galleries}/></div>
}

function ItemFields({ id, name, kind, draft, captions, onUpdate }: { id: string; name: string; kind: Kind; draft: ItemDraft | undefined; captions: readonly MediaAssetView[]; onUpdate: (id: string, field: keyof ItemDraft, value: string) => void }): React.ReactElement { return <fieldset className="border border-outline-variant bg-surface-container-low p-4"><legend className="px-2 text-xs font-bold uppercase tracking-[.1em] text-primary-ink">Describe {name}</legend><div className="grid gap-3 md:grid-cols-2"><label><span className="mb-1 block text-xs font-bold">Caption</span><input required value={draft?.caption ?? ''} onChange={(event) => { onUpdate(id, 'caption', event.target.value) }} placeholder="Who, what, where and when" className="h-11 w-full border border-outline-variant bg-surface px-3"/></label><label><span className="mb-1 block text-xs font-bold">Credit</span><input value={draft?.credit ?? ''} onChange={(event) => { onUpdate(id, 'credit', event.target.value) }} placeholder="Photographer or newsroom" className="h-11 w-full border border-outline-variant bg-surface px-3"/></label></div>{kind === 'video' && <Choice label="Synchronized captions" items={captions.map((item) => ({ id: item.id, label: item.filename }))} selected={draft?.captionAssetID ?? ''} onSelect={(captionID) => { onUpdate(id, 'captionAssetID', captionID) }}/>}</fieldset> }
function GalleryList({ galleries }: { galleries: readonly GalleryView[] }): React.ReactElement { return <section className="border border-outline-variant bg-surface-container-lowest p-6 shadow-[8px_9px_0_rgba(16,75,42,.12)]"><p className="broadcast-kicker text-primary">Public catalogue</p><h2 className="mt-2 font-display text-3xl font-bold">Published galleries</h2>{galleries.length === 0 ? <Empty text="The first visual story will appear here with complete captions and credits."/> : <div className="mt-6 space-y-4">{galleries.map((gallery) => <article key={gallery.id} className="border border-outline-variant bg-surface-container-low p-5"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-primary-ink">{gallery.kind} · {gallery.media.length} items</span><h3 className="mt-2 font-display text-2xl font-bold">{gallery.title}</h3><p className="mt-2 text-sm text-on-surface-variant">{gallery.summary}</p></article>)}</div>}</section> }
function Choice({ label, items, selected, onSelect }: { label: string; items: readonly { id: string; label: string }[]; selected: string; onSelect: (id: string) => void }): React.ReactElement { return <fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">{label}</legend><div className="flex flex-wrap gap-2">{items.map((item) => <button key={item.id} type="button" aria-pressed={selected === item.id} onClick={() => { onSelect(item.id) }} className={`border px-3 py-2 text-xs font-bold ${selected === item.id ? 'border-primary bg-primary text-on-primary' : 'border-outline-variant hover:border-primary'}`}>{item.label}</button>)}</div>{items.length === 0 && <p className="text-sm text-error">No ready assets are available.</p>}</fieldset> }
function Field({ name, label, placeholder }: { name: string; label: string; placeholder: string }): React.ReactElement { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">{label}</span><input name={name} required placeholder={placeholder} className="h-12 w-full border border-outline-variant bg-surface px-4 focus:border-primary focus:outline-none"/></label> }
function TextArea({ name, label, placeholder }: { name: string; label: string; placeholder: string }): React.ReactElement { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">{label}</span><textarea name={name} required rows={4} placeholder={placeholder} className="w-full border border-outline-variant bg-surface p-4 focus:border-primary focus:outline-none"/></label> }
function Empty({ text }: { text: string }): React.ReactElement { return <div className="signal-grid mt-6 border border-outline-variant p-8 text-center"><span aria-hidden className="mx-auto grid size-12 animate-pulse place-items-center bg-primary text-xl text-on-primary">▧</span><h3 className="mt-4 font-display text-xl font-bold">The visual desk is ready.</h3><p className="mt-2 text-sm text-on-surface-variant">{text}</p></div> }
function Dots(): React.ReactElement { return <span aria-hidden className="inline-flex gap-1"><i className="size-1 animate-bounce rounded-full bg-current"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:120ms]"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:240ms]"/></span> }
function value(data: FormData, name: string): string { const item = data.get(name); return typeof item === 'string' ? item : '' }
function slug(value: string): string { return value.toLowerCase().normalize('NFKD').replace(/\p{M}/gu, '').trim().replace(/[^a-z0-9]+/gu, '-').replace(/^-|-$/gu, '') }
function formatBytes(bytes: number): string { return bytes < 1_000_000 ? `${String(Math.round(bytes / 1_000))} KB` : `${(bytes / 1_000_000).toFixed(1)} MB` }
