'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import type { MembershipPlanView } from '@kurasikapa/web-kit/bff/revenue'
import { createMembershipPlanAction } from '@/actions/revenue'

export function MembershipManager({ plans }: { readonly plans: readonly MembershipPlanView[] }): React.ReactElement {
  const router = useRouter()
  const [interval, setInterval] = useState<'monthly' | 'yearly'>('monthly')
  const [currency, setCurrency] = useState<'GHS' | 'EUR'>('GHS')
  const [pending, setPending] = useState(false)
  const [notice, setNotice] = useState<string | null>(null)

  async function submit(form: FormData): Promise<void> {
    setPending(true); setNotice(null)
    const benefits = formText(form, 'benefits').split('\n').map((value) => value.trim()).filter(Boolean)
    const amount = Number(form.get('amount'))
    const result = await createMembershipPlanAction({ name: form.get('name'), slug: form.get('slug'), description: form.get('description'), interval, currency, amountMinor: Math.round(amount * 100), benefits })
    if (result.ok) { setNotice('Membership tier activated and visible on the public support page.'); router.refresh() }
    else setNotice(result.error.message)
    setPending(false)
  }

  return <div className="space-y-8"><header className="grid gap-5 border-b-4 border-on-surface pb-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="broadcast-kicker text-primary">Revenue desk</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-.04em] md:text-6xl">Memberships</h1><p className="mt-3 max-w-2xl text-on-surface-variant">Create recurring support tiers. Activation is explicit, checkout stays with Paystack or Stripe, and pending payments grant no access.</p></div><div className="broadcast-shadow border-2 border-outline bg-surface-container-lowest px-6 py-4"><strong className="block font-display text-3xl">{plans.length}</strong><span className="text-xs font-bold uppercase tracking-[.12em] text-on-surface-variant">Active tiers</span></div></header>
    <div className="grid gap-7 xl:grid-cols-[.9fr_1.1fr]"><form action={(data) => { void submit(data) }} className="space-y-5 border-2 border-outline bg-surface-container-lowest p-6 md:p-8"><div><p className="broadcast-kicker text-secondary-ink">New tier</p><h2 className="mt-2 font-display text-2xl font-semibold">Publish a membership offer</h2></div><Field label="Tier name"><input name="name" required placeholder="e.g. Newsroom Supporter" className="h-13 w-full border-2 border-outline px-4 focus:border-primary focus:outline-none" /></Field><Field label="URL slug"><input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="newsroom-supporter" className="h-13 w-full border-2 border-outline px-4 focus:border-primary focus:outline-none" /></Field><Field label="Public description"><textarea name="description" required minLength={20} maxLength={500} placeholder="Explain what this tier funds and who it is for" className="min-h-28 w-full border-2 border-outline p-4 focus:border-primary focus:outline-none" /></Field><Choice label="Billing interval" value={interval} options={['monthly', 'yearly']} onChange={(value) => { setInterval(value as typeof interval) }} /><Choice label="Currency" value={currency} options={['GHS', 'EUR']} onChange={(value) => { setCurrency(value as typeof currency) }} /><Field label={`Amount in ${currency}`}><div className="flex items-center border-2 border-outline focus-within:border-primary"><span className="px-4 font-bold text-primary">{currency}</span><input name="amount" required type="number" min="5" step="0.01" placeholder="35.00" className="h-13 w-full border-0 px-2 outline-none" /></div></Field><Field label="Benefits — one per line"><textarea name="benefits" required placeholder={'Member briefings\nAd-light reading\nSupporter updates'} className="min-h-32 w-full border-2 border-outline p-4 focus:border-primary focus:outline-none" /></Field>{notice !== null && <p role="status" className="border-l-4 border-secondary bg-secondary-container px-4 py-3 text-sm">{notice}</p>}<button disabled={pending} className="flex min-h-13 w-full items-center justify-between bg-primary px-5 font-bold text-on-primary disabled:opacity-45"><span>{pending ? <>Publishing tier <LoadingDots /></> : 'Create and activate tier'}</span><span aria-hidden>↗</span></button></form>
      <section aria-labelledby="active-tiers"><h2 id="active-tiers" className="font-display text-2xl font-semibold">Active offers</h2>{plans.length > 0 ? <div className="mt-4 grid gap-4 md:grid-cols-2">{plans.map((plan) => <article key={plan.id} className="broadcast-shadow flex min-h-64 flex-col border-2 border-outline bg-surface-container-lowest p-6"><p className="broadcast-kicker text-primary">{plan.interval}</p><h3 className="mt-3 font-display text-2xl font-semibold">{plan.name}</h3><p className="mt-3 text-sm leading-6 text-on-surface-variant">{plan.description}</p><p className="mt-auto pt-6 font-display text-3xl font-bold">{new Intl.NumberFormat('en', { style: 'currency', currency: plan.price.currency }).format(plan.price.minor / 100)}</p></article>)}</div> : <div className="signal-grid mt-4 border-2 border-outline bg-surface-container-low p-10 text-center"><span aria-hidden className="inline-block animate-pulse text-5xl text-primary">◈</span><h3 className="mt-4 font-display text-xl font-semibold">No active membership tiers</h3><p className="mt-2 text-sm text-on-surface-variant">Create the first offer to populate the public support page.</p></div>}</section></div>
  </div>
}

function Field({ label, children }: { readonly label: string; readonly children: React.ReactNode }): React.ReactElement { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-on-surface-variant">{label}</span>{children}</label> }
function Choice({ label, value, options, onChange }: { readonly label: string; readonly value: string; readonly options: readonly string[]; readonly onChange: (value: string) => void }): React.ReactElement { return <fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-[.12em] text-on-surface-variant">{label}</legend><div className="inline-flex border-2 border-outline">{options.map((option) => <button key={option} type="button" aria-pressed={value === option} onClick={() => { onChange(option) }} className={`px-5 py-3 text-xs font-bold uppercase ${value === option ? 'bg-primary text-on-primary' : 'bg-surface text-on-surface'}`}>{option}</button>)}</div></fieldset> }
function LoadingDots(): React.ReactElement { return <span aria-hidden className="ml-2 inline-flex gap-1"><i className="size-1 animate-bounce rounded-full bg-current"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:120ms]"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:240ms]"/></span> }
function formText(form: FormData, key: string): string { const value = form.get(key); return typeof value === 'string' ? value : '' }
