'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import type { MediaAssetView } from '@kurasikapa/web-kit/bff/media-library'
import type { PodcastView } from '@kurasikapa/web-kit/bff/podcasts'
import { createEpisodeAction, createPodcastAction } from '@/actions/podcasts'

export function PodcastManager({ locale, podcasts, assets }: { locale: string; podcasts: readonly PodcastView[]; assets: readonly MediaAssetView[] }): React.ReactElement {
  return <div className="grid gap-7 xl:grid-cols-2"><SeriesForm locale={locale} assets={assets}/><EpisodeForm locale={locale} podcasts={podcasts} assets={assets}/><Library podcasts={podcasts}/></div>
}

function SeriesForm({ locale, assets }: { locale: string; assets: readonly MediaAssetView[] }): React.ReactElement {
  const router = useRouter(); const [artwork, setArtwork] = useState(''); const [message, setMessage] = useState<string | null>(null); const [pending, start] = useTransition()
  const submit = (data: FormData): void => { start(async () => {
    const title = value(data, 'title'); const result = await createPodcastAction({ title, slug: slug(title), locale, summary: value(data, 'summary'), author: value(data, 'author'), ...(artwork === '' ? {} : { artworkAssetID: artwork }) })
    if (!result.ok) { setMessage(result.error.message); return }
    setMessage('Podcast series published.'); router.refresh()
  }) }
  return <Panel eyebrow="Series desk" title="Create a podcast"><form action={submit} className="space-y-4"><Field name="title" label="Series title" placeholder="The Kurasikapa Brief"/><Field name="author" label="Editorial author" placeholder="Kurasikapa Newsroom"/><TextArea name="summary" label="Series summary" placeholder="Explain the editorial promise, format and audience."/><AssetChoice label="Cover artwork" kind="image" assets={assets} selected={artwork} onSelect={setArtwork} optional/><Submit pending={pending} label="Create and publish series"/>{message !== null && <Status>{message}</Status>}</form></Panel>
}

function EpisodeForm({ locale, podcasts, assets }: { locale: string; podcasts: readonly PodcastView[]; assets: readonly MediaAssetView[] }): React.ReactElement {
  const router = useRouter(); const [podcastID, setPodcast] = useState(podcasts[0]?.id ?? ''); const [audio, setAudio] = useState(''); const [transcript, setTranscript] = useState(''); const [message, setMessage] = useState<string | null>(null); const [pending, start] = useTransition()
  const submit = (data: FormData): void => { start(async () => {
    const title = value(data, 'title'); const durationSeconds = Number(value(data, 'durationSeconds')); const chapters = parseChapters(value(data, 'chapters'))
    const result = await createEpisodeAction({ podcastID, title, slug: slug(title), locale, summary: value(data, 'summary'), audioAssetID: audio, transcriptAssetID: transcript, durationSeconds, chapters })
    if (!result.ok) { setMessage(result.error.message); return }
    setMessage('Episode published with accessible audio and transcript.'); router.refresh()
  }) }
  return <Panel eyebrow="Episode desk" title="Publish an episode">{podcasts.length === 0 ? <Status>Create and publish a podcast series first.</Status> : <form action={submit} className="space-y-4"><Choice label="Podcast series" items={podcasts.map((item) => ({ id: item.id, label: item.title }))} selected={podcastID} onSelect={setPodcast}/><Field name="title" label="Episode title" placeholder="Market close: what changed this week"/><TextArea name="summary" label="Episode summary" placeholder="Give listeners a precise reason to press play."/><Field name="durationSeconds" label="Duration in seconds" placeholder="1800" inputMode="numeric"/><AssetChoice label="Verified audio" kind="audio" assets={assets} selected={audio} onSelect={setAudio}/><AssetChoice label="Transcript" kind="transcript" assets={assets} selected={transcript} onSelect={setTranscript}/><TextArea name="chapters" label="Chapters" placeholder={'00:00 Opening\n05:30 Main interview\n18:10 What happens next'}/><Submit pending={pending || audio === '' || transcript === '' || podcastID === ''} label="Publish accessible episode"/>{message !== null && <Status>{message}</Status>}</form>}</Panel>
}

function Library({ podcasts }: { podcasts: readonly PodcastView[] }): React.ReactElement {
  return <section className="border border-outline-variant bg-surface-container-lowest p-6 shadow-[8px_9px_0_rgba(16,75,42,.12)] xl:col-span-2"><p className="broadcast-kicker text-primary">Public catalogue</p><h2 className="mt-2 font-display text-3xl font-bold">Published podcasts</h2>{podcasts.length === 0 ? <div className="signal-grid mt-6 border border-outline-variant p-8 text-center"><span aria-hidden className="mx-auto grid size-12 animate-pulse place-items-center bg-primary text-on-primary">♪</span><h3 className="mt-4 font-display text-xl font-bold">The audio desk is ready.</h3><p className="mt-2 text-sm text-on-surface-variant">Your first published series and accessible episode will appear here.</p></div> : <div className="mt-6 grid gap-4 md:grid-cols-2">{podcasts.map((item) => <article key={item.id} className="border border-outline-variant bg-surface-container-low p-5"><h3 className="font-display text-2xl font-bold">{item.title}</h3><p className="mt-2 text-sm text-on-surface-variant">{item.summary}</p><p className="mt-4 text-xs font-bold uppercase text-primary-ink">{item.episodes.length} episodes</p></article>)}</div>}</section>
}

function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }): React.ReactElement { return <section className="border border-outline-variant bg-surface-container-lowest p-6 shadow-[8px_9px_0_rgba(16,75,42,.12)]"><p className="broadcast-kicker text-primary">{eyebrow}</p><h2 className="mb-6 mt-2 font-display text-3xl font-bold">{title}</h2>{children}</section> }
function Field({ name, label, placeholder, inputMode }: { name: string; label: string; placeholder: string; inputMode?: 'numeric' }): React.ReactElement { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">{label}</span><input name={name} required inputMode={inputMode} placeholder={placeholder} className="h-12 w-full border border-outline-variant bg-surface px-4 focus:border-primary focus:outline-none"/></label> }
function TextArea({ name, label, placeholder }: { name: string; label: string; placeholder: string }): React.ReactElement { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">{label}</span><textarea name={name} required rows={4} placeholder={placeholder} className="w-full border border-outline-variant bg-surface p-4 focus:border-primary focus:outline-none"/></label> }
function AssetChoice({ label, kind, assets, selected, onSelect, optional = false }: { label: string; kind: string; assets: readonly MediaAssetView[]; selected: string; onSelect: (id: string) => void; optional?: boolean }): React.ReactElement { const items = assets.filter((item) => item.kind === kind && item.status === 'ready'); return <Choice label={label} items={[...(optional ? [{ id: '', label: 'No artwork yet' }] : []), ...items.map((item) => ({ id: item.id, label: item.filename }))]} selected={selected} onSelect={onSelect}/> }
function Choice({ label, items, selected, onSelect }: { label: string; items: readonly { id: string; label: string }[]; selected: string; onSelect: (id: string) => void }): React.ReactElement { return <fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-[.1em] text-on-surface-variant">{label}</legend><div className="flex flex-wrap gap-2">{items.map((item) => <button key={`${item.id}-${item.label}`} type="button" aria-pressed={selected === item.id} onClick={() => { onSelect(item.id) }} className={`border px-3 py-2 text-xs font-bold ${selected === item.id ? 'border-primary bg-primary text-on-primary' : 'border-outline-variant hover:border-primary'}`}>{item.label}</button>)}</div>{items.length === 0 && <p className="text-sm text-error">Upload a ready {label.toLowerCase()} asset in Media Library first.</p>}</fieldset> }
function Submit({ pending, label }: { pending: boolean; label: string }): React.ReactElement { return <button disabled={pending} className="bg-primary px-5 py-3 text-sm font-bold text-on-primary disabled:cursor-wait disabled:opacity-45">{pending ? <span className="inline-flex items-center gap-2">Publishing <Dots/></span> : label}</button> }
function Dots(): React.ReactElement { return <span aria-hidden className="inline-flex gap-1"><i className="size-1 animate-bounce rounded-full bg-current"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:120ms]"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:240ms]"/></span> }
function Status({ children }: { children: React.ReactNode }): React.ReactElement { return <p role="status" className="border-l-4 border-secondary bg-secondary-container/30 p-3 text-sm">{children}</p> }
function value(data: FormData, name: string): string { const item = data.get(name); return typeof item === 'string' ? item : '' }
function slug(value: string): string { return value.toLowerCase().trim().replace(/[^a-z0-9]+/gu, '-').replace(/^-|-$/gu, '') }
function parseChapters(value: string): { title: string; startsAtSec: number }[] { return value.split('\n').map((line) => line.trim()).filter(Boolean).map((line) => { const match = /^(\d{1,2}):(\d{2})\s+(.+)$/u.exec(line); if (match === null) return { title: line, startsAtSec: -1 }; return { title: match[3] ?? '', startsAtSec: Number(match[1]) * 60 + Number(match[2]) } }) }
