import type { RevenueCurrencyView, RevenueReportView, SubscriberView } from '@kurasikapa/web-kit/bff/revenue'
import { Link } from '@kurasikapa/web-kit/i18n/navigation'

export function RevenueDashboard({ report }: { readonly report: RevenueReportView }): React.ReactElement {
  const primary = report.currencies.find((item) => item.currency === 'GHS') ?? empty('GHS')
  const secondary = report.currencies.find((item) => item.currency === 'EUR') ?? empty('EUR')
  const metrics = [
    { label: 'Active members', value: report.activeSubscribers.toLocaleString(), detail: 'Paid-through entitlement' },
    { label: 'GHS collected', value: format(primary.grossMinor, 'GHS'), detail: `MRR ${format(primary.mrrMinor, 'GHS')}` },
    { label: 'EUR collected', value: format(secondary.grossMinor, 'EUR'), detail: `MRR ${format(secondary.mrrMinor, 'EUR')}` },
    { label: 'Successful gifts', value: report.successfulDonations.toLocaleString(), detail: `Last ${String(report.days)} days` },
  ]
  return <section className="space-y-7" aria-labelledby="revenue-performance"><header className="flex flex-wrap items-end justify-between gap-4 border-b-2 border-on-surface pb-5"><div><p className="broadcast-kicker text-primary">Revenue intelligence</p><h2 id="revenue-performance" className="mt-2 font-display text-3xl font-semibold">Performance and subscribers</h2><p className="mt-2 text-sm text-on-surface-variant">Confirmed provider payments only. GHS and EUR remain separate—no invented exchange rate.</p></div><nav aria-label="Revenue period" className="flex border-2 border-outline">{[7, 30, 90].map((days) => <Link key={days} href={`/revenue?days=${String(days)}`} aria-current={report.days === days ? 'page' : undefined} className={`px-4 py-3 text-xs font-bold ${report.days === days ? 'bg-primary text-on-primary' : 'bg-surface-container-lowest'}`}>{days} days</Link>)}</nav></header>
    <div className="depth-grid grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric, index) => <article key={metric.label} className={`min-h-36 border-b-2 border-on-surface p-5 shadow-[7px_8px_0_rgba(16,75,42,.12)] ${index === 0 ? 'bg-primary text-on-primary' : 'bg-surface-container-lowest'}`}><p className="text-xs font-bold uppercase tracking-[.14em] opacity-70">{metric.label}</p><strong className="mt-5 block font-display text-3xl tabular-nums">{metric.value}</strong><p className="mt-2 text-xs opacity-70">{metric.detail}</p></article>)}</div>
    <div className="depth-grid grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><RevenueChart report={report} /><Mix summaries={[primary, secondary]} /></div>
    <SubscriberLedger rows={report.subscribers} pending={report.pendingSubscribers} canceled={report.canceledSubscribers} />
  </section>
}

function RevenueChart({ report }: { readonly report: RevenueReportView }): React.ReactElement {
  const max = Math.max(1, ...report.trend.map((point) => point.minor))
  return <article className="border-b-2 border-on-surface bg-surface-container-lowest p-6 shadow-[7px_8px_0_rgba(16,75,42,.12)]"><p className="broadcast-kicker text-primary">Confirmed cashflow</p><h3 className="mt-2 font-display text-2xl font-semibold">Payment activity</h3>{report.trend.length === 0 ? <Empty title="No confirmed payments in this period" description="Successful membership and donation webhooks will build this chart." /> : <div className="mt-8 flex h-48 items-end gap-2" role="img" aria-label="Confirmed revenue by day and currency"><span className="sr-only">{report.trend.map((point) => `${point.date}: ${format(point.minor, point.currency)}`).join('; ')}</span>{report.trend.map((point, index) => <span key={`${point.date}-${point.currency}-${String(index)}`} title={`${point.date}: ${format(point.minor, point.currency)}`} className={`min-w-2 flex-1 ${point.currency === 'GHS' ? 'bg-primary' : 'bg-secondary'}`} style={{ height: `${String(Math.max(8, point.minor / max * 100))}%` }}/>)}</div>}</article>
}

function Mix({ summaries }: { readonly summaries: readonly RevenueCurrencyView[] }): React.ReactElement {
  return <article className="border-b-2 border-on-surface bg-surface-container-lowest p-6 shadow-[7px_8px_0_rgba(16,75,42,.12)]"><p className="broadcast-kicker text-secondary-ink">Revenue mix</p><h3 className="mt-2 font-display text-2xl font-semibold">Memberships and gifts</h3><div className="mt-7 space-y-6">{summaries.map((item) => { const total = Math.max(1, item.grossMinor); return <div key={item.currency}><div className="flex justify-between gap-3"><strong>{item.currency}</strong><span className="font-mono text-sm">{format(item.grossMinor, item.currency)}</span></div><div className="mt-2 flex h-4 bg-surface-container-high"><span className="bg-primary" style={{ width: `${String(item.subscriptionMinor / total * 100)}%` }}/><span className="bg-secondary" style={{ width: `${String(item.donationMinor / total * 100)}%` }}/></div><p className="mt-2 text-xs text-on-surface-variant">Membership {format(item.subscriptionMinor, item.currency)} · Gifts {format(item.donationMinor, item.currency)}</p></div> })}</div></article>
}

function SubscriberLedger({ rows, pending, canceled }: { readonly rows: readonly SubscriberView[]; readonly pending: number; readonly canceled: number }): React.ReactElement {
  return <article className="border-2 border-outline bg-surface-container-lowest"><div className="flex flex-wrap justify-between gap-4 border-b-2 border-outline p-6"><div><p className="broadcast-kicker text-primary">Subscriber ledger</p><h3 className="mt-2 font-display text-2xl font-semibold">Recent membership journeys</h3></div><p className="text-sm text-on-surface-variant">{pending} pending · {canceled} canceled</p></div>{rows.length === 0 ? <div className="p-6"><Empty title="No membership journeys yet" description="Checkout starts and confirmed subscriptions will appear here without manufacturing demo revenue." /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-surface-container-low"><tr>{['Subscriber', 'Status', 'Plan', 'Value', 'Started', 'Access through'].map((label) => <th key={label} className="px-5 py-3 text-xs uppercase tracking-[.12em]">{label}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-outline-variant"><td className="px-5 py-4"><strong className="block">{row.email || 'Email unavailable'}</strong><span className="text-xs text-on-surface-variant">{row.readerId}</span></td><td className="px-5 py-4"><span className="border border-outline px-2 py-1 text-xs font-bold uppercase">{row.status}</span></td><td className="px-5 py-4 font-mono text-xs">{row.planId}</td><td className="px-5 py-4 font-bold">{format(row.price.minor, row.price.currency)}</td><td className="px-5 py-4">{date(row.startedAt)}</td><td className="px-5 py-4">{row.paidThrough === null ? 'Awaiting payment' : date(row.paidThrough)}</td></tr>)}</tbody></table></div>}</article>
}

function Empty({ title, description }: { readonly title: string; readonly description: string }): React.ReactElement { return <div className="signal-grid border border-dashed border-outline p-8 text-center"><span aria-hidden className="inline-block animate-pulse text-4xl text-primary">◈</span><h4 className="mt-3 font-display text-lg font-semibold">{title}</h4><p className="mt-2 text-sm text-on-surface-variant">{description}</p></div> }
function empty(currency: 'GHS' | 'EUR'): RevenueCurrencyView { return { currency, grossMinor: 0, subscriptionMinor: 0, donationMinor: 0, mrrMinor: 0 } }
function format(minor: number, currency: 'GHS' | 'EUR'): string { return new Intl.NumberFormat('en-GH', { style: 'currency', currency }).format(minor / 100) }
function date(value: string): string { const parsed = new Date(value); return Number.isNaN(parsed.valueOf()) ? '—' : new Intl.DateTimeFormat('en-GH', { dateStyle: 'medium' }).format(parsed) }
