'use client'

import Image from 'next/image'
import { useRouter } from 'next/navigation'
import { useMemo, useState, useTransition } from 'react'
import { publishStaffProfileAction } from '@/actions/staff-profiles'

interface Person { readonly id: string; readonly name: string; readonly email: string; readonly roles: readonly string[] }
interface Asset { readonly id: string; readonly locale: string; readonly altText: string; readonly secureUrl: string }

export function StaffProfileManager({ people, assets }: { people: readonly Person[]; assets: readonly Asset[] }): React.ReactElement {
  const router = useRouter(); const [pending, start] = useTransition()
  const [userId, setUserId] = useState(people[0]?.id ?? ''); const [locale, setLocale] = useState<'en' | 'fr'>('en')
  const [portrait, setPortrait] = useState(''); const [message, setMessage] = useState<string | null>(null)
  const candidates = people.filter((person) => person.roles.some((role) => ['super_admin', 'administrator', 'editor', 'journalist', 'author'].includes(role)))
  const portraits = useMemo(() => assets.filter((asset) => asset.locale === locale), [assets, locale])
  const submit = (data: FormData): void => { start(async () => {
    const result = await publishStaffProfileAction({ userId, locale, portraitAssetId: portrait, displayName: value(data, 'displayName'), jobTitle: value(data, 'jobTitle'), biography: value(data, 'biography'), socialLabel: value(data, 'socialLabel'), socialUrl: value(data, 'socialUrl') })
    setMessage(result.ok ? 'Public profile published.' : result.error.message)
    if (result.ok) router.refresh()
  }) }
  return <section className="border-y-2 border-on-surface bg-surface-container-lowest"><header className="signal-grid border-b border-outline-variant p-5 md:p-7"><p className="broadcast-kicker text-primary">Institutional credibility</p><h2 className="mt-2 font-display text-3xl font-semibold">Publish a newsroom profile</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-on-surface-variant">Connect a verified team member to a public biography and media-library portrait. Publishing makes the profile available on Team, author pages and article bylines.</p></header>
    <form action={submit} className="space-y-6 p-5 md:p-7"><ChoiceGroup label="Team member" items={candidates.map((person) => ({ id: person.id, title: person.name || person.email, detail: person.roles.join(' · ') }))} selected={userId} onSelect={setUserId} empty="Invite and assign a newsroom role before publishing a profile." /><ChoiceGroup label="Profile language" items={[{ id: 'en', title: 'English', detail: 'EN' }, { id: 'fr', title: 'French', detail: 'FR' }]} selected={locale} onSelect={(id) => { setLocale(id === 'fr' ? 'fr' : 'en'); setPortrait('') }} /><div className="grid gap-4 md:grid-cols-2"><Field name="displayName" label="Public name" placeholder="Ama Mensah" /><Field name="jobTitle" label="Newsroom role" placeholder="Senior political reporter" /></div><Area /><PortraitPicker rows={portraits} selected={portrait} onSelect={setPortrait} /><div className="grid gap-4 md:grid-cols-2"><Field name="socialLabel" label="Public link label" placeholder="LinkedIn" required={false} /><Field name="socialUrl" label="HTTPS public link" placeholder="https://…" required={false} type="url" /></div><div className="flex flex-wrap items-center gap-4"><button disabled={pending || userId === '' || portrait === ''} className="min-w-56 bg-primary px-6 py-3 text-sm font-bold text-on-primary disabled:cursor-wait disabled:opacity-45">{pending ? <span className="inline-flex items-center gap-2">Publishing <Dots /></span> : 'Publish public profile'}</button>{message !== null && <p role="status" className="border-l-4 border-secondary bg-secondary-container/30 p-3 text-sm">{message}</p>}</div></form>
  </section>
}

function ChoiceGroup({ label, items, selected, onSelect, empty }: { label: string; items: readonly { id: string; title: string; detail: string }[]; selected: string; onSelect: (id: string) => void; empty?: string }): React.ReactElement { return <fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-[.14em] text-on-surface-variant">{label}</legend><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <button key={item.id} type="button" aria-pressed={selected === item.id} onClick={() => { onSelect(item.id) }} className={`border p-3 text-left transition ${selected === item.id ? 'border-primary bg-primary-container shadow-[4px_4px_0_var(--color-primary)]' : 'border-outline-variant hover:border-primary'}`}><strong className="block text-sm">{item.title}</strong><span className="mt-1 block text-xs text-on-surface-variant">{item.detail}</span></button>)}</div>{items.length === 0 && <p className="bg-surface-container-low p-4 text-sm text-on-surface-variant">{empty}</p>}</fieldset> }
function PortraitPicker({ rows, selected, onSelect }: { rows: readonly Asset[]; selected: string; onSelect: (id: string) => void }): React.ReactElement { return <fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-[.14em] text-on-surface-variant">Verified portrait</legend><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{rows.map((asset) => <button key={asset.id} type="button" aria-pressed={selected === asset.id} onClick={() => { onSelect(asset.id) }} className={`relative aspect-[4/5] overflow-hidden border-2 ${selected === asset.id ? 'border-secondary ring-4 ring-secondary/20' : 'border-transparent'}`}><Image src={asset.secureUrl} alt={asset.altText} fill sizes="180px" className="object-cover" /></button>)}</div>{rows.length === 0 && <p className="bg-surface-container-low p-4 text-sm text-on-surface-variant">Upload and verify an image for this language in Media library first.</p>}</fieldset> }
function Field({ name, label, placeholder, required = true, type = 'text' }: { name: string; label: string; placeholder: string; required?: boolean; type?: string }): React.ReactElement { return <label><span className="mb-2 block text-xs font-bold uppercase tracking-[.14em] text-on-surface-variant">{label}</span><input name={name} type={type} required={required} placeholder={placeholder} className="h-12 w-full border border-outline-variant bg-surface px-4 outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" /></label> }
function Area(): React.ReactElement { return <label><span className="mb-2 block text-xs font-bold uppercase tracking-[.14em] text-on-surface-variant">Biography</span><textarea name="biography" required minLength={40} rows={5} placeholder="Describe this journalist’s beat, experience and public responsibility." className="w-full border border-outline-variant bg-surface p-4 outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" /></label> }
function Dots(): React.ReactElement { return <span aria-hidden className="inline-flex gap-1"><i className="size-1 animate-bounce rounded-full bg-current"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:120ms]"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:240ms]"/></span> }
function value(data: FormData, name: string): string { const found = data.get(name); return typeof found === 'string' ? found : '' }
