'use client'

import { useRouter } from 'next/navigation'
import { useState, useTransition } from 'react'
import { createPresenterAction, createProgrammeAction, scheduleProgrammeAction } from '@/actions/television'

interface PresenterItem { readonly id: string; readonly name: string; readonly role: string }
interface ProgrammeItem { readonly id: string; readonly title: string; readonly category: string; readonly presenters: readonly PresenterItem[] }
interface SlotItem { readonly id: string; readonly title: string; readonly startsAt: string; readonly isLive: boolean }

export function TelevisionManager(props: { locale: string; presenters: readonly PresenterItem[]; programmes: readonly ProgrammeItem[]; upcoming: readonly SlotItem[] }): React.ReactElement {
  return <div className="grid gap-7 xl:grid-cols-2"><PresenterForm locale={props.locale} /><ProgrammeForm locale={props.locale} presenters={props.presenters} /><ScheduleForm locale={props.locale} programmes={props.programmes} /><ScheduleLedger locale={props.locale} rows={props.upcoming} /></div>
}

function PresenterForm({ locale }: { locale: string }): React.ReactElement {
  const run = useAction(createPresenterAction)
  return <Panel eyebrow="On-screen identity" title="Add a presenter" description="Publish a verified presenter profile with a role and client-approved biography."><form action={(data) => { run.submit({ name: value(data, 'name'), slug: slug(value(data, 'name')), locale, role: value(data, 'role'), biography: value(data, 'biography') }) }} className="space-y-4"><Text name="name" label="Full name" placeholder="Ama Nyarko" /><Text name="role" label="On-screen role" placeholder="Host, The Civic Desk" /><Area name="biography" label="Biography" placeholder="Describe their reporting background, beat and responsibility." /><Submit pending={run.pending} label="Publish presenter" />{run.message !== null && <Status message={run.message} />}</form></Panel>
}

function ProgrammeForm({ locale, presenters }: { locale: string; presenters: readonly PresenterItem[] }): React.ReactElement {
  const run = useAction(createProgrammeAction)
  const [selected, setSelected] = useState<string[]>([])
  return <Panel eyebrow="Programme directory" title="Create a programme" description="Define a recurring format before adding it to the transmission schedule."><form action={(data) => { run.submit({ title: value(data, 'title'), slug: slug(value(data, 'title')), locale, summary: value(data, 'summary'), category: value(data, 'category'), presenterIds: selected }) }} className="space-y-4"><Text name="title" label="Programme title" placeholder="The Civic Desk" /><Text name="category" label="Format" placeholder="Current affairs" /><Area name="summary" label="Public summary" placeholder="Tell viewers what this programme covers and why they should watch." /><fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-[.12em] text-on-surface-variant">Presenters</legend><div className="grid gap-2 sm:grid-cols-2">{presenters.map((item) => <button key={item.id} type="button" aria-pressed={selected.includes(item.id)} onClick={() => { setSelected(toggle(selected, item.id)) }} className={`border p-3 text-left ${selected.includes(item.id) ? 'border-primary bg-primary-container' : 'border-outline-variant'}`}><strong className="block text-sm">{item.name}</strong><span className="text-xs text-on-surface-variant">{item.role}</span></button>)}</div>{presenters.length === 0 && <p className="border-l-4 border-secondary bg-secondary-container/30 p-3 text-sm">Publish a presenter first. Programmes cannot go public without an accountable host.</p>}</fieldset><Submit pending={run.pending} disabled={selected.length === 0} label="Publish programme" />{run.message !== null && <Status message={run.message} />}</form></Panel>
}

function ScheduleForm({ locale, programmes }: { locale: string; programmes: readonly ProgrammeItem[] }): React.ReactElement {
  const run = useAction(scheduleProgrammeAction)
  const [programme, setProgramme] = useState('')
  const [isLive, setIsLive] = useState(true)
  return <Panel eyebrow="Transmission planning" title="Schedule an airing" description="Add the next live or prerecorded slot. Viewers can download a 15-minute calendar reminder."><form action={(data) => { run.submit({ programmeId: programme, locale, startsAt: value(data, 'startsAt'), endsAt: value(data, 'endsAt'), isLive }) }} className="space-y-4"><fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-[.12em] text-on-surface-variant">Programme</legend><div className="grid gap-2">{programmes.map((item) => <button key={item.id} type="button" aria-pressed={programme === item.id} onClick={() => { setProgramme(item.id) }} className={`border p-3 text-left ${programme === item.id ? 'border-primary bg-primary-container' : 'border-outline-variant'}`}><strong>{item.title}</strong><span className="ml-2 text-xs text-on-surface-variant">{item.category}</span></button>)}</div></fieldset><div className="grid gap-4 sm:grid-cols-2"><Text name="startsAt" label="Starts" type="datetime-local" /><Text name="endsAt" label="Ends" type="datetime-local" /></div><fieldset><legend className="mb-2 text-xs font-bold uppercase tracking-[.12em] text-on-surface-variant">Transmission type</legend><div className="flex border border-outline">{[{ value: true, label: 'Live' }, { value: false, label: 'Prerecorded' }].map((item) => <button key={item.label} type="button" aria-pressed={isLive === item.value} onClick={() => { setIsLive(item.value) }} className={`flex-1 px-4 py-3 text-xs font-bold uppercase ${isLive === item.value ? 'bg-primary text-on-primary' : ''}`}>{item.label}</button>)}</div></fieldset><Submit pending={run.pending} disabled={programme === ''} label="Add to schedule" />{run.message !== null && <Status message={run.message} />}</form></Panel>
}

function ScheduleLedger({ locale, rows }: { locale: string; rows: readonly SlotItem[] }): React.ReactElement {
  return <Panel eyebrow="Public guide" title="Upcoming transmissions" description="This is the same indexed schedule now available to the reader-facing Live page.">{rows.length === 0 ? <div className="signal-grid border border-outline-variant bg-surface-container-low p-6"><span aria-hidden className="inline-grid size-11 animate-pulse place-items-center bg-primary text-on-primary">▶</span><h3 className="mt-4 font-display text-xl font-bold">The transmission board is clear.</h3><p className="mt-2 text-sm text-on-surface-variant">Schedule the first programme to populate the public guide.</p></div> : <div className="space-y-2">{rows.map((row) => <article key={row.id} className="grid grid-cols-[5rem_1fr] border border-outline-variant bg-surface-container-lowest"><time className="bg-primary p-3 text-center text-xs font-bold text-on-primary">{new Date(row.startsAt).toLocaleDateString(locale, { month: 'short', day: 'numeric' })}</time><div className="p-3"><strong className="block">{row.title}</strong><span className="text-xs text-on-surface-variant">{new Date(row.startsAt).toLocaleTimeString(locale, { hour: '2-digit', minute: '2-digit' })} · {row.isLive ? 'Live' : 'Prerecorded'}</span></div></article>)}</div>}</Panel>
}

function useAction(action: (input: unknown) => Promise<{ ok: boolean; data?: unknown; error?: { message: string } }>): { pending: boolean; message: string | null; submit: (input: unknown) => void } {
  const router = useRouter()
  const [pending, start] = useTransition()
  const [message, setMessage] = useState<string | null>(null)
  const submit = (input: unknown): void => { start(async () => { const result = await action(input); setMessage(result.ok ? 'Published successfully.' : result.error?.message ?? 'Unable to save.'); if (result.ok) router.refresh() }) }
  return { pending, message, submit }
}

function Panel({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }): React.ReactElement { return <section className="border border-outline-variant bg-surface-container-lowest shadow-[7px_8px_0_rgba(16,75,42,.1)]"><header className="signal-grid border-b border-outline-variant p-5"><p className="broadcast-kicker text-primary">{eyebrow}</p><h2 className="mt-2 font-display text-2xl font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-on-surface-variant">{description}</p></header><div className="p-5">{children}</div></section> }
function Text({ name, label, placeholder, type = 'text' }: { name: string; label: string; placeholder?: string; type?: string }): React.ReactElement { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-on-surface-variant">{label}</span><input name={name} type={type} required placeholder={placeholder} className="h-12 w-full border border-outline-variant bg-surface px-4 focus:border-primary focus:outline-none" /></label> }
function Area({ name, label, placeholder }: { name: string; label: string; placeholder: string }): React.ReactElement { return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-on-surface-variant">{label}</span><textarea name={name} required minLength={20} rows={4} placeholder={placeholder} className="w-full border border-outline-variant bg-surface p-4 focus:border-primary focus:outline-none" /></label> }
function Submit({ pending, label, disabled = false }: { pending: boolean; label: string; disabled?: boolean }): React.ReactElement { return <button disabled={pending || disabled} className="min-w-52 bg-primary px-5 py-3 text-sm font-bold text-on-primary disabled:cursor-wait disabled:opacity-45">{pending ? <span className="inline-flex items-center gap-2">Saving <Dots /></span> : label}</button> }
function Dots(): React.ReactElement { return <span aria-hidden className="inline-flex gap-1"><i className="size-1 animate-bounce rounded-full bg-current"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:120ms]"/><i className="size-1 animate-bounce rounded-full bg-current [animation-delay:240ms]"/></span> }
function Status({ message }: { message: string }): React.ReactElement { return <p role="status" className="border-l-4 border-secondary bg-secondary-container/30 p-3 text-sm">{message}</p> }
function value(data: FormData, name: string): string { const found = data.get(name); return typeof found === 'string' ? found : '' }
function slug(valueToSlug: string): string { return valueToSlug.toLowerCase().trim().replace(/[^a-z0-9]+/gu, '-').replace(/(^-|-$)/gu, '') }
function toggle(values: readonly string[], target: string): string[] { return values.includes(target) ? values.filter((item) => item !== target) : [...values, target] }
