import { createHash, randomBytes, timingSafeEqual } from 'node:crypto'
import type { SecretGenerator } from '@kurasikapa/application'

/**
 * Randomness and fast hashing for values that are not passwords.
 *
 * Refresh tokens, recovery codes, OAuth `state` and PKCE verifiers are all
 * generated by us at full entropy, so there is nothing to brute force and a
 * slow KDF would buy nothing but latency. SHA-256 is the right tool here and
 * exactly the wrong one for a password — which is why they are two ports.
 */
export class NodeSecretGenerator implements SecretGenerator {
  token(bytes: number): string {
    // base64url: safe in a URL, a cookie and a header without escaping, which
    // matters because these values travel through all three.
    return randomBytes(bytes).toString('base64url')
  }

  sha256(value: string): string {
    return createHash('sha256').update(value, 'utf8').digest('hex')
  }

  /**
   * Constant-time comparison of two strings.
   *
   * Hashes both sides first. `timingSafeEqual` throws on a length mismatch,
   * and that throw leaks length — hashing makes both inputs 32 bytes whatever
   * was passed in, so the comparison is total and the timing is flat.
   */
  equals(a: string, b: string): boolean {
    const left = createHash('sha256').update(a, 'utf8').digest()
    const right = createHash('sha256').update(b, 'utf8').digest()

    return timingSafeEqual(left, right)
  }
}
