import type { Metadata } from 'next'
import Image from 'next/image'
import { setRequestLocale } from 'next-intl/server'
import { loadEvents, type EventView } from '@kurasikapa/web-kit/bff/events'

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params
  return { title: locale === 'fr' ? 'Événements et sommets | Kurasikapa Media TV' : 'Events and summits | Kurasikapa Media TV', description: locale === 'fr' ? 'Webinaires, conversations publiques et sommets de la rédaction Kurasikapa.' : 'Kurasikapa newsroom webinars, public conversations, conferences and summits.' }
}

export default async function EventsPage({ params }: { params: Promise<{ locale: string }> }): Promise<React.ReactElement> {
  const { locale } = await params; setRequestLocale(locale); const events = await loadEvents(locale); const french = locale === 'fr'
  const featured = events.find((event) => event.featured) ?? events[0]; const remaining = featured === undefined ? [] : events.filter((event) => event.id !== featured.id)
  return <main className="bg-[#07140d] text-white"><section className="mx-auto max-w-[var(--container-page)] px-5 py-12 md:px-8 md:py-20">{featured === undefined ? <Empty french={french}/> : <><EventSchema event={featured}/><Feature event={featured} french={french}/><section className="mt-16"><div className="flex flex-col justify-between gap-4 border-b border-white/15 pb-5 md:flex-row md:items-end"><div><p className="broadcast-kicker text-secondary">{french ? 'Webinaires et conférences' : 'Webinars & conferences'}</p><h2 className="mt-2 font-display text-4xl font-bold">{french ? 'Prochaines sessions' : 'Upcoming sessions'}</h2></div><p className="max-w-lg text-sm leading-6 text-white/55">{french ? 'Des rencontres de la rédaction avec des horaires clairs, des intervenants identifiés et des liens d’inscription vérifiés.' : 'Newsroom-led gatherings with clear timing, accountable speakers and verified registration links.'}</p></div>{remaining.length === 0 ? <p className="signal-grid mt-8 border border-white/15 p-8 text-center text-white/60">{french ? 'Cette rencontre est la seule session annoncée pour le moment.' : 'This is the only announced session for now. More will appear after editorial approval.'}</p> : <div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{remaining.map((event) => <EventCard key={event.id} event={event} french={french}/>)}</div>}</section></>}</section></main>
}

function Feature({ event, french }: { event: EventView; french: boolean }): React.ReactElement { return <article className="relative min-h-[32rem] overflow-hidden border border-white/15 bg-[#10251a] shadow-[12px_14px_0_rgba(255,179,182,.14)] md:min-h-[38rem]">{event.image !== null && <Image src={event.image.url} alt={event.image.altText} fill priority sizes="(max-width: 1200px) 100vw, 1200px" className="object-cover opacity-55"/>}<div className="absolute inset-0 bg-gradient-to-t from-[#07140d] via-[#07140d]/65 to-transparent"/><div className="relative z-10 flex min-h-[32rem] max-w-4xl flex-col justify-end p-7 md:min-h-[38rem] md:p-14"><span className="w-fit border border-secondary px-3 py-1 text-[10px] font-bold tracking-[.14em] text-secondary uppercase">{french ? 'Événement à la une' : 'Featured event'}</span><p className="mt-6 text-xs font-bold tracking-[.14em] text-white/65 uppercase">{event.type} · {event.mode.replace('_',' ')}</p><h1 className="mt-3 font-display text-5xl font-bold leading-[.9] tracking-[-.05em] md:text-7xl">{event.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">{event.summary}</p><EventFacts event={event}/><div className="mt-8 flex flex-wrap gap-3"><Registration event={event} french={french}/><a href={calendarUrl(event)} target="_blank" rel="noreferrer" className="border border-white/30 bg-white/8 px-6 py-3 text-xs font-bold tracking-[.1em] uppercase hover:border-secondary">{french ? 'Ajouter au calendrier' : 'Add to calendar'}</a></div></div></article> }
function EventCard({ event, french }: { event: EventView; french: boolean }): React.ReactElement { return <article className="flex h-full flex-col overflow-hidden border border-white/15 bg-white/[.04] shadow-[7px_8px_0_rgba(255,179,182,.08)]"><div className="relative h-48 bg-[#10251a]">{event.image !== null && <Image src={event.image.url} alt={event.image.altText} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover"/>}<span className="absolute left-4 top-4 bg-[#07140d]/90 px-3 py-1 text-[10px] font-bold tracking-[.12em] uppercase">{event.type}</span></div><div className="flex flex-1 flex-col p-6"><p className="text-xs font-bold text-secondary">{formatDate(event.startsAt)}</p><h3 className="mt-3 font-display text-2xl font-bold leading-tight">{event.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-white/60">{event.summary}</p><p className="mt-5 border-t border-white/10 pt-4 text-xs text-white/55">{place(event)}{event.speakers.length > 0 ? ` · ${event.speakers.join(', ')}` : ''}</p><div className="mt-5 flex flex-wrap gap-2"><Registration event={event} french={french}/><a href={calendarUrl(event)} target="_blank" rel="noreferrer" className="border border-white/25 px-4 py-2 text-[10px] font-bold uppercase">{french ? 'Calendrier' : 'Calendar'}</a></div></div></article> }
function EventFacts({ event }: { event: EventView }): React.ReactElement { return <dl className="mt-7 grid max-w-3xl gap-4 border-t border-white/15 pt-5 text-sm sm:grid-cols-3"><div><dt className="text-[10px] font-bold tracking-[.12em] text-secondary uppercase">Date</dt><dd className="mt-1 text-white/75">{formatDate(event.startsAt)}</dd></div><div><dt className="text-[10px] font-bold tracking-[.12em] text-secondary uppercase">Place</dt><dd className="mt-1 text-white/75">{place(event)}</dd></div><div><dt className="text-[10px] font-bold tracking-[.12em] text-secondary uppercase">Speakers</dt><dd className="mt-1 text-white/75">{event.speakers.join(', ') || 'To be announced'}</dd></div></dl> }
function Registration({ event, french }: { event: EventView; french: boolean }): React.ReactElement { return event.registrationUrl === '' ? <span className="bg-white/10 px-5 py-3 text-xs font-bold tracking-[.1em] text-white/55 uppercase">{french ? 'Inscription bientôt' : 'Registration soon'}</span> : <a href={event.registrationUrl} target="_blank" rel="noopener noreferrer" className="bg-secondary px-5 py-3 text-xs font-bold tracking-[.1em] text-on-secondary uppercase hover:brightness-105">{french ? 'S’inscrire' : 'Register now'}</a> }
function Empty({ french }: { french: boolean }): React.ReactElement { return <section className="signal-grid flex min-h-[34rem] items-center justify-center border border-white/15 p-8 text-center"><div><span aria-hidden className="mx-auto grid size-16 animate-pulse place-items-center border border-secondary text-3xl text-secondary">◇</span><p className="mt-6 text-xs font-bold tracking-[.16em] text-secondary uppercase">Kurasikapa Events</p><h1 className="mt-3 font-display text-5xl font-bold">{french ? 'La prochaine rencontre se prépare.' : 'The next gathering is taking shape.'}</h1><p className="mx-auto mt-4 max-w-2xl leading-7 text-white/60">{french ? 'Les webinaires, conversations publiques et sommets apparaîtront ici après validation éditoriale.' : 'Approved webinars, public conversations and summits will appear here with speakers, schedules and registration details.'}</p></div></section> }
function EventSchema({ event }: { event: EventView }): React.ReactElement {
  const data = {
    '@context': 'https://schema.org', '@type': 'Event', name: event.title, description: event.summary,
    startDate: event.startsAt, endDate: event.endsAt, eventAttendanceMode: attendance(event.mode),
    eventStatus: 'https://schema.org/EventScheduled', image: event.image === null ? undefined : [event.image.url],
    location: event.mode === 'online'
      ? { '@type': 'VirtualLocation', url: event.registrationUrl }
      : { '@type': 'Place', name: event.venue, address: { '@type': 'PostalAddress', addressLocality: event.city, addressCountry: 'GH' } },
    performer: event.speakers.map((name) => ({ '@type': 'Person', name })),
    offers: event.registrationUrl === '' ? undefined : { '@type': 'Offer', url: event.registrationUrl, availability: 'https://schema.org/InStock' },
  }
  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replaceAll('<','\\u003c') }}/>
}
function attendance(mode: EventView['mode']): string { return mode === 'online' ? 'https://schema.org/OnlineEventAttendanceMode' : mode === 'in_person' ? 'https://schema.org/OfflineEventAttendanceMode' : 'https://schema.org/MixedEventAttendanceMode' }
function place(event: EventView): string { return event.mode === 'online' ? 'Online' : [event.venue,event.city].filter(Boolean).join(', ') }
function formatDate(input: string): string { return new Intl.DateTimeFormat('en-GH', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Africa/Accra' }).format(new Date(input)) }
function calendarUrl(event: EventView): string { const dates = `${compact(event.startsAt)}/${compact(event.endsAt)}`; return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(event.title)}&dates=${dates}&details=${encodeURIComponent(event.summary)}&location=${encodeURIComponent(place(event))}` }
function compact(input: string): string { return new Date(input).toISOString().replaceAll('-','').replaceAll(':','').replace('.000','') }
