'use client'

import { useState } from 'react'
import type { AffiliateLinkView } from '@kurasikapa/web-kit/bff/revenue'
import { followAffiliateAction } from '@/actions/affiliates'

export function AffiliateMarket({ links }: { readonly links: readonly AffiliateLinkView[] }): React.ReactElement {
  const [pending, setPending] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  async function follow(id: string): Promise<void> { setPending(id); setError(null); const result = await followAffiliateAction({ id }); if (result.ok) window.location.assign(result.data.destinationURL); else { setError(result.error.message); setPending(null) } }
  return <main><section className="signal-grid border-b border-outline px-5 py-20 sm:px-10"><div className="mx-auto max-w-7xl"><p className="broadcast-kicker text-primary">Reader resources</p><h1 className="mt-4 max-w-4xl font-display text-6xl font-semibold leading-none sm:text-8xl">Partner recommendations</h1><p className="mt-6 max-w-2xl text-lg text-on-surface-variant">Products and services selected by the newsroom’s commercial team. Every paid relationship is disclosed clearly.</p></div></section><section className="mx-auto max-w-7xl px-5 py-14 sm:px-10">{links.length === 0 ? <div className="signal-grid border-2 border-outline p-12 text-center"><span aria-hidden className="inline-block animate-pulse text-5xl text-primary">◇</span><h2 className="mt-4 font-display text-3xl font-semibold">Recommendations are being prepared</h2><p className="mx-auto mt-3 max-w-xl text-on-surface-variant">Only reviewed, useful partner offers will appear here.</p></div> : <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{links.map((link) => <article key={link.id} className="overflow-hidden border-2 border-outline bg-surface-container-lowest shadow-[8px_8px_0_var(--color-outline)]"><img src={link.imageURL} alt={link.imageAlt} className="aspect-[16/10] w-full object-cover"/><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-primary">{link.category} · {link.partner}</p><h2 className="mt-3 font-display text-3xl font-semibold">{link.title}</h2><p className="mt-3 text-on-surface-variant">{link.description}</p><p className="mt-5 border-l-4 border-secondary pl-3 text-xs font-semibold">{link.disclosure}</p><button type="button" disabled={pending !== null} onClick={() => { void follow(link.id) }} className="mt-6 min-h-13 w-full bg-primary px-5 font-bold text-on-primary disabled:opacity-45">{pending === link.id ? 'Opening partner •••' : 'Visit partner ↗'}</button></div></article>)}</div>}{error && <p role="alert" className="mt-8 border-l-4 border-error bg-error-container p-4">{error}</p>}</section></main>
}
