'use client'

import { useState } from 'react'
import type { ClassifiedView, ProductView } from '@kurasikapa/web-kit/bff/revenue'
import { startClassifiedAction, startProductAction } from '@/actions/revenue-actions'

export function ProductShop({ products, locale }: { readonly products: readonly ProductView[]; readonly locale: string }): React.ReactElement {
  const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null)
  async function buy(productID: string, form: FormData): Promise<void> { setBusy(productID); setMessage(null); const result = await startProductAction({ productID, quantity: Number(form.get('quantity')), email: form.get('email'), deliveryName: form.get('name'), deliveryAddress: form.get('address'), locale: locale === 'fr' ? 'fr' : 'en' }); if (result.ok) window.location.assign(result.data.checkoutURL); else { setMessage(result.error.message); setBusy(null) } }
  return <main className="mx-auto max-w-[var(--container-page)] px-4 py-12 md:px-8"><Header kicker="Publisher shop" title="Stories and objects worth keeping." copy="Official Kurasikapa publications and merchandise. Checkout is secured by Stripe in EUR or Paystack in GHS." />{message && <p role="alert" className="mb-6 border-l-4 border-error bg-error-container p-4">{message}</p>}{products.length === 0 ? <Empty title="The shop is being stocked" copy="Official products will appear after the revenue desk activates them." /> : <div className="depth-grid grid gap-6 md:grid-cols-2 xl:grid-cols-3">{products.map((product) => <article key={product.id} className="broadcast-shadow flex flex-col border-2 border-outline bg-surface-container-lowest p-6"><img src={product.imageURL} alt={product.imageAlt} className="aspect-[4/3] w-full object-cover"/><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-primary">{product.sku} · {product.stock} available</p><h2 className="mt-2 font-display text-3xl font-semibold">{product.name}</h2><p className="mt-3 text-sm leading-6 text-on-surface-variant">{product.description}</p><strong className="mt-5 font-display text-3xl">{format(product.price)}</strong><form action={(data) => { void buy(product.id, data) }} className="mt-6 space-y-3"><input name="name" required placeholder="Delivery name" className={field}/><input name="email" required type="email" placeholder="Receipt email" className={field}/><textarea name="address" required minLength={10} placeholder="Delivery address" className={`${field} min-h-24 py-3`}/><input name="quantity" type="number" min="1" max={Math.min(20, product.stock)} defaultValue="1" className={field}/><Submit busy={busy === product.id} label="Buy securely" /></form></article>)}</div>}</main>
}

export function ClassifiedMarket({ listings, locale }: { readonly listings: readonly ClassifiedView[]; readonly locale: string }): React.ReactElement {
  const [currency, setCurrency] = useState<'GHS' | 'EUR'>('GHS'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null)
  async function submit(form: FormData): Promise<void> { setBusy(true); setMessage(null); const result = await startClassifiedAction({ title: form.get('title'), category: form.get('category'), description: form.get('description'), location: form.get('location'), contactName: form.get('contactName'), contactEmail: form.get('contactEmail'), contactPhone: form.get('contactPhone'), imageURL: form.get('imageURL'), amountMinor: Math.round(Number(form.get('amount')) * 100), currency, locale: locale === 'fr' ? 'fr' : 'en' }); if (result.ok) window.location.assign(result.data.checkoutURL); else { setMessage(result.error.message); setBusy(false) } }
  return <main className="mx-auto max-w-[var(--container-page)] px-4 py-12 md:px-8"><Header kicker="Community noticeboard" title="Classifieds, reviewed before they go live." copy="A listing runs for 30 days. Payment starts the review; it never bypasses newsroom approval." /><div className="grid gap-10 xl:grid-cols-[1.1fr_.9fr]"><section>{listings.length === 0 ? <Empty title="No approved listings today" copy="Submit a relevant notice using the form. Paid submissions remain private until reviewed." /> : <div className="depth-grid grid gap-5 md:grid-cols-2">{listings.map((item) => <article key={item.id} className="border-2 border-outline bg-surface-container-lowest p-6 shadow-[7px_8px_0_rgba(16,75,42,.12)]"><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">{item.category} · {item.location}</p><h2 className="mt-3 font-display text-2xl font-semibold">{item.title}</h2><p className="mt-3 text-sm leading-6 text-on-surface-variant">{item.description}</p><strong className="mt-5 block font-display text-2xl">{format(item.askingPrice)}</strong><p className="mt-4 text-sm">Contact {item.contactName} · <a className="underline" href={`mailto:${item.contactEmail}`}>{item.contactEmail}</a></p></article>)}</div>}</section><form action={(data) => { void submit(data) }} className="space-y-4 border-2 border-outline bg-surface-container-lowest p-6"><h2 className="font-display text-3xl font-semibold">Submit a listing</h2><input name="title" required placeholder="Clear listing title" className={field}/><input name="category" required placeholder="Category" className={field}/><textarea name="description" required minLength={30} placeholder="Describe the item or opportunity accurately" className={`${field} min-h-32 py-3`}/><input name="location" required placeholder="Location" className={field}/><input name="contactName" required placeholder="Contact name" className={field}/><input name="contactEmail" required type="email" placeholder="Contact email" className={field}/><input name="contactPhone" placeholder="Phone (optional)" className={field}/><input name="imageURL" type="url" placeholder="https:// image (optional)" className={field}/><div className="flex border-2 border-outline">{(['GHS','EUR'] as const).map((value) => <button key={value} type="button" aria-pressed={currency === value} onClick={() => { setCurrency(value) }} className={`flex-1 p-3 font-bold ${currency === value ? 'bg-primary text-on-primary' : ''}`}>{value}</button>)}</div><input name="amount" required type="number" min="1" step="0.01" placeholder="Asking price" className={field}/>{message && <p role="alert" className="border-l-4 border-error p-3">{message}</p>}<Submit busy={busy} label="Pay placement and submit" /></form></div></main>
}

const field = 'min-h-13 w-full border-2 border-outline bg-surface px-4 outline-none focus:border-primary'
function Header({ kicker, title, copy }: { readonly kicker: string; readonly title: string; readonly copy: string }): React.ReactElement { return <header className="mb-10 border-b-4 border-on-surface pb-8"><p className="eyebrow text-primary">{kicker}</p><h1 className="mt-3 max-w-4xl font-display text-5xl font-semibold md:text-7xl">{title}</h1><p className="mt-5 max-w-2xl leading-7 text-on-surface-variant">{copy}</p></header> }
function Empty({ title, copy }: { readonly title: string; readonly copy: string }): React.ReactElement { return <div className="signal-grid border-2 border-outline p-12 text-center"><span aria-hidden className="inline-block animate-pulse text-5xl text-primary">◈</span><h2 className="mt-4 font-display text-2xl font-semibold">{title}</h2><p className="mt-2 text-on-surface-variant">{copy}</p></div> }
function Submit({ busy, label }: { readonly busy: boolean; readonly label: string }): React.ReactElement { return <button disabled={busy} className="flex min-h-13 w-full items-center justify-between bg-primary px-5 font-bold text-on-primary disabled:opacity-45"><span>{busy ? <>Opening checkout <i className="ml-2 inline-block animate-pulse">•••</i></> : label}</span><span aria-hidden>↗</span></button> }
function format(value: { readonly minor: number; readonly currency: 'GHS' | 'EUR' }): string { return new Intl.NumberFormat('en', { style: 'currency', currency: value.currency }).format(value.minor / 100) }
